config/routes.rb
Rails.application.routes.draw do

  
  get 'users/new'


   root 'pages#home'

   get '/contact' => 'pages#contact'

   get '/about' => 'pages#about'

   resources :meals
   
   resources :movies

   resources :cars

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   delete '/logout' => 'sessions#destroy'

   get '/signup' => 'users#new'
   post '/signup' => 'users#create'

end

app/models/car.rb
class Car < ActiveRecord::Base






end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  belongs_to :meal
end

app/models/meal.rb
class Meal < ActiveRecord::Base

  has_many :ingredients

  validates :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base


  enum membership: [:basic, :plus, :pro]
  has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  

def current_user

  @current_user ||= User.where(id: session[:user_id]).first
end
helper_method :current_user
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [:edit, :update, :show, :destroy]


def index
  @cars = Car.all
end

def create
   @car = Car.new(car_params)
      if @car.save 
        # it returned true. Do stuff
        redirect_to cars_path
    else
        # it returned false. Do different stuff
      render :new
     end
  
end

def new
  @car = Car.new
end

def edit
  @car
  
end

def show
  
end

def update
  if @car.update(car_params)
    redirect_to car_path
  else
    render :edit
  end
end

def destroy
  @car.destroy
  redirect_to cars_path
  
end

private

def car_params
      params.require(:car).permit(:year, :make, :vehicle_model, :body, :engine)
      
end

    def find_car
      @car = Car.find(params[:id])

    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
before_action :find_meal, only: [:edit, :update, :show, :destroy]


def index
  @meals = Meal.all
end

def create
   @meal = Meal.new(meal_params)
      if @meal.save 
        # it returned true. Do stuff
        redirect_to meals_path
    else
        # it returned false. Do different stuff
      render :new
     end
  
end

def new
  @meal = Meal.new
end

def edit
  @Meal
  
end

def show
  
end

def update
  if @meal.update(meal_params)
    redirect_to meal_path
  else
    render :edit
  end
end

def destroy
  @meal.destroy
  redirect_to meals_path
  
end

private

def meal_params
      params.require(:meal).permit(:name, :calories, :prep_time, :restaurant,)
      
end

    def find_meal
      @meal = Meal.find(params[:id])

    end

end

app/controllers/movies_controller.rb
  class MoviesController < ApplicationController
    before_action :find_movie, only: [:edit, :update, :show, :destroy]


    # to display a collection of movies
    def index
      @movies = Movie.all
    end

    #display form to create a new movie
    def new
      @movie = Movie.new
      
    end

    # the logic to store new data into the database
    def create
      @movie = Movie.new(movie_params)
      if @movie.save 
        # it returned true. Do stuff
        redirect_to movies_path
    else
        # it returned false. Do different stuff
      render :new
     end
    end
        

    
    # to display a form to update an existing movie
    def edit
    end

    # the logic to alter the data of an existing movie in the database
    def update
      if @movie.update(movie_params)
        redirect_to movies_path
      else
        render :edit
      end
    end


    # to display data from a specific movie
    def show
    end

    #to remove data from the database
    def destroy
      @movie.destroy
      redirect_to movies_path
    end

    private

    def movie_params
      params.require(:movie).permit(:title, :released_at)
      
    end

    def find_movie
      @movie = Movie.find(params[:id])

    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

  def contact
    
  end

  def about
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    @user = User.where(username: params[:username]).first
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome, you got mail"
    else
      flash[:alert] = "Wrong username or password"
      render :new
    end
  end

    def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'YAY! welcome!!'
    else
      flash[:alert] = 'boo. that did not work'
      render :new
       
    end
  end


private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :membership)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_for_page(scope)
    controller, action = *scope.split('#')
    if params[:controller] == controller && params[:action] == action
      return "active"
    end
  end

  def user_signed_in?
    current_user.present?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/edit.html.erb
<%= form_for(@car) do |f| %>

  <p>Year: <%= f.select(:year, 1949..2015)%></p>
  <p>Make: <%= f.text_field(:make)%></p>
  <p>Model: <%= f.text_field(:vehicle_model)%></p>
  <p>Body: <%= f.text_field(:body)%></p>
  <p>Engine: <%= f.text_field(:engine)%></p>

 <p><h1><%= f.submit('Save') %></h1></p>

<% end %>

app/views/cars/index.html.erb
  <%= link_to('Add new car', new_car_path ) %>

    <div class="">

    <% @cars.each do |car| %>
    <p>
      <h1><%= link_to(car.make, car_path(car.id)) %></h1>
      <span><%= car.year %></span>
      <span><%= car.make %></span>
      <span><%= car.vehicle_model %></span>
      <span><%= car.body %></span>
      <span><%= car.engine %></span>
     <p>
      <%= link_to('edit this car', edit_car_path(car.id))%>
      <%= link_to('delete this car', car_path(car.id), method: :delete) %> 
    <% end %>
  </div>

  

app/views/cars/new.html.erb
<%= form_for(@car) do |f| %>

  <p>Year: <%= f.select(:year, 1949..2015)%></p>
  <p>Make: <%= f.text_field(:make)%></p>
  <p>Model: <%= f.text_field(:vehicle_model)%></p>
  <p>Body: <%= f.text_field(:body)%></p>
  <p>Engine: <%= f.text_field(:engine)%></p>

 <p><h1><%= f.submit('Save') %></h1></p>

<% end %>

app/views/cars/show.html.erb
<h1><%= @car.make %></h1>

 <%= link_to "Back", :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <div class="container">
<body> 
        <%= image_tag "stuff/brown-sandbox2.jpg" %>
    <div class="row">
      <div class="col-sm-12">
        <header>
          <%= render ('shared/top_nav') %>
        </header>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <section>

        <%= yield %>
    
        </section>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <hr />
         <footer>
          <div id="fixedfooter">
            copyright &copy; <%= Time.now.year %>
          </div>
        </footer>
      </div>
    </div>

    
    </body>
  </div>
</html>

app/views/meals/edit.html.erb
<%= form_for(@meal) do |f| %>

  <p>Name: <%= f.text_field(:name)%></p>
  <p>Calories: <%= f.text_field(:calories)%></p>
  <p>Prep_time: <%= f.text_field(:prep_time)%></p>
  <p>Restaurant: <%= f.text_field(:restaurant)%></p>
  

 <p><h1><%= f.submit('Update') %></h1></p>

<% end %>

app/views/meals/index.html.erb
<div>
  <%= link_to('create', new_meal_path, class: "glyphicon glyphicon-plus") %>
  </a>

</div>

<h1 class="page-header"> All meals page!</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Calories</th>
        <th>Restaurant</th>
        <th>Prep Time</th>
        <th>&nbsp;</th>

      </tr>
    </thead> 
    <tbody>
      <% @meals.each do |meal| %>
        <tr>
         <td><%= link_to(meal.name, meal_path(meal.id)) %></td>
         <td><%= meal.calories %></td>
         <td><%= meal.prep_time %></td>
         <td><%= meal.restaurant %></td>
         <td>
          
          <a href="<%= edit_meal_path(meal.id) %>" class="btn btn-warning">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
          <%= link_to('delete', meal_path(meal.id),method: :delete, class: "btn btn-danger") %>

         </td>



        </tr>
      <% end %>
     </tbody>
   </table>

app/views/meals/new.html.erb
<%= form_for(@meal) do |f| %>

  <p>Name: <%= f.text_field(:name)%></p>
  <p>Calories: <%= f.text_field(:calories)%></p>
  <p>Prep_time: <%= f.text_field(:prep_time)%></p>
  <p>Restaurant: <%= f.text_field(:restaurant)%></p>
  

 <p><h1><%= f.submit('Save') %></h1></p>

<% end %>

app/views/meals/show.html.erb
<h1><%= @meal.name %></h1>

app/views/movies/edit.html.erb
<%= form_for(@movie) do |f| %>

  <p>Title: <%= f.text_field(:title)%></p>
  <p>Released</p>
  <p><%= f.datetime_select(:released_at, start_year:1980, order: [:month, :year], ampm: false)%></p>
  <p><h1><%= f.submit('Update') %></h1></p>

<% end %>

app/views/movies/index.html.erb
  <%= link_to('Create new movie', new_movie_path ) %>

  <ul>
    <% @movies.each do |movie| %>
      <li>
        <h1><%= link_to(movie.title, movie_path(movie.id)) %></h1>
        <%= movie.released_at.strftime("%b %d, %Y") %>
        <%= link_to('edit this movie', edit_movie_path(movie.id))%>
        <%= link_to('delete this movie', movie_path(movie.id), method: :delete) %>
      </li>
      <% end %>
  </ul>

app/views/movies/new.html.erb
<%= form_for(@movie) do |f| %>

  <p>Title: <%= f.text_field(:title)%></p>
  <p>Released</p>
  <p><%= f.date_select(:released_at, start_year:1980, ampm:false)%></p>
  <p><h1><%= f.submit('Save') %></h1></p>

<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

 <%= link_to "Back", :back %>

app/views/pages/about.html.erb
this is our About page!

app/views/pages/contact.html.erb
this is our Contact us page!

app/views/pages/home.html.erb
  <title>Sandbox</title>


<% if user_signed_in? %>
  <h1 class="page-header">Welcome, <%= current_user.username %></h1>

  <% if current_user.pro? %>
  You mad, pro?
  <% end %>

  <p>
    Membership: <%= current_user.membership %>
  </p>
<% else %>
  <p class="lead">
    You should log in
    <%= link_to('Login', login_path, class: 'btn btn-success')%>
  </p>
  <% end %>

app/views/shared/_top_nav.html.erb
          <ul class="nav nav-pills">
            <li class="<%= active_for_page('pages#home') %>">
              <%= link_to 'Home', root_path %>
            </li>
            <li class="<%= active_for_page('pages#about') %>">
              <a href="<%= about_path %>">About Page</a>
            </li>
            <li class="<%= active_for_page('pages#contact') %>">
              <a href="<%= contact_path %>">Contact Page</a>
            </li>
            <% if user_signed_in? %>
            <li class="<%= active_for_page('meals#index') %>">
              <%= link_to 'Meals', meals_path %>
            </li>
            <li class="<%= active_for_page('movies#index') %>">
              <%= link_to 'Movies', movies_path %>
            </li>
            <li class="<%= active_for_page('cars#index') %>">
              <%= link_to 'Cars', cars_path%>
            </li>
            <li>
              <a href=" <%= logout_path %>" data-method="delete" class= "text-danger">Logout</a>
            </li>
            <% else %>
             <li class="<%= active_for_page('sessions#new') %>">
              <%= link_to 'Login', login_path%>
            </li>
            <li class="<%= active_for_page('user#new') %>">
              <%= link_to 'Sign Up', signup_path%>
              <% end %>

app/views/users/new.html.erb
<h1 class="page-header">Sign up!</h1>
<%= form_for(@user, url: signup_path, html: {class: 'form'}) do |f| %>
  <div class="form_group">
    <%= f.label(:username, class: 'form-label') %>
    <%= f.text_field(:username, class: 'form-control') %>
  </div>
  <div class="form_group">
   <%= f.label(:password, class: 'form-label') %>
   <%= f.password_field(:password, class: 'form-control') %>
  </div>
  <div class="form_group">
    <%= f.label(:password_confirmation, class: 'form-label') %>
    <%= f.password_field(:password_confirmation, class: 'form-control') %>
  </div>
  <div class="form_group">
    <%= f.label(:membership, class: 'form-label') %>
    <%= f.select(:membership, options_for_select(['basic', 'plus', 'pro'])) %>
  </div>
  <div class="form_group">
    <%= f.submit('Signup', class: 'btn btn-lg btn-success') %>
 </div> 

<% end %>